# Generated by Django 5.2.1 on 2025-09-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.CharField(max_length=64)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('addr', models.CharField(max_length=16)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['sheet', 'row'], name='aiproject_s_sheet_2d833f_idx'), models.Index(fields=['sheet', 'col'], name='aiproject_s_sheet_eb067e_idx')],
                'unique_together': {('sheet', 'addr')},
            },
        ),
    ]
