# Generated by Django 5.2.1 on 2025-10-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiproject', '0002_sheetcell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('price_range', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.BooleanField(default=False)),
                ('find_answer', models.BooleanField(default=False)),
                ('search', models.BooleanField(default=False)),
                ('code', models.BooleanField(default=False)),
                ('support_text', models.BooleanField(default=False)),
                ('image', models.BooleanField(default=False)),
                ('motion_image', models.BooleanField(default=False)),
                ('vedio', models.BooleanField(default=False)),
                ('user_personal', models.BooleanField(default=False)),
                ('user_team', models.BooleanField(default=False)),
                ('support_chinese', models.BooleanField(default=False)),
                ('yearly_discount', models.BooleanField(default=False)),
                ('upload_data', models.BooleanField(default=False)),
                ('upload_data_note', models.TextField(blank=True, null=True)),
                ('make_data', models.BooleanField(default=False)),
                ('make_data_note', models.TextField(blank=True, null=True)),
                ('make_image', models.BooleanField(default=False)),
                ('make_image_note', models.TextField(blank=True, null=True)),
                ('vedio_make', models.BooleanField(default=False)),
                ('motion_image_make', models.BooleanField(default=False)),
                ('delete_logo', models.BooleanField(default=False)),
                ('for_personal', models.BooleanField(default=False)),
                ('for_business', models.BooleanField(default=False)),
                ('user_limit', models.TextField(blank=True, null=True)),
                ('manufacture', models.BooleanField(default=False)),
                ('retail', models.BooleanField(default=False)),
                ('government', models.BooleanField(default=False)),
                ('law', models.BooleanField(default=False)),
                ('realestate', models.BooleanField(default=False)),
                ('education', models.BooleanField(default=False)),
                ('healthcare', models.BooleanField(default=False)),
                ('technology', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('media', models.BooleanField(default=False)),
                ('design', models.BooleanField(default=False)),
                ('finance', models.BooleanField(default=False)),
            ],
        ),
    ]
