# Generated by Django 5.2.1 on 2025-11-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiproject', '0003_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='logo_file',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
