# Generated by Django 5.2.1 on 2025-11-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiproject', '0004_tool_logo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
